import { datetime } from './general';
import { languages } from './voice_messages';

export interface StartConversationParameter {
  /** The type of the message content. */
  type: string;
  /** Content of the message to send. The value of type defines the required fields. */
  content: Content;
  /** An channel-specific identifier for the receiver. For example: a mobile phone number (MSISDN) is valid for SMS or Whatsapp channels. */
  to?: string;
  /** The unique ID that identifies the channel over which the message should be sent. */
  channelId?: string;
}

export interface ConversationParameter {
  /** Either a channel-specific identifier for the receiver (e.g. MSISDN for SMS or WhatsApp channels), or the ID of a MessageBird Contact. */
  to: string;

  /** The ID that identifies the channel over which the message should be sent. */
  from: string;

  /** The type of the message content. */
  type: string;

  /** Content of the message. The value of type defines the required fields. */
  content: Content;

  /** The URL for delivery of status reports for the message. Must be HTTPS. */
  reportUrl: string;
}

export type Content =
  | TextContent
  | ImageContent
  | AudioContent
  | FileContent
  | LocationContent
  | HSMContent;

export interface TextContent {
  /** Required for type text. The plain-text content of the message. */
  text: string;
}

export interface ImageContent {
  /** Required for type image. An object of the form {"url": "<media url>"} containing the url of the remote media file. */
  image: File;
}

export interface AudioContent {
  /** Required for type video. An object of the form {"url": "<media url>"} containing the url of the remote media file. */
  video: File;
}

export interface FileContent {
  /** Required for type file. An object of the form {"url": "<media url>"} containing the url of the remote media file. */
  file: File;
}

export interface File {
  url: string;
}

export interface LocationContent {
  /** Latitude and longitude are expected as floats. */
  location: {
    latitude: number;
    longitude: number;
  };
}

export interface HSMContent {
  /** Required for type hsm. Available only for WhatsApp. */
  hsm: HSMContentContent;
}

export interface HSMContentContent {
  /** WhatsApp namespace for your account. You will receive this value when setting up your WhatsApp account. */
  namespace: string;

  /** The name of the template. */
  templateName: string;
  language: HSMLanguage;
  params: HSMLocalizableParameters[];
}

export interface HSMLanguage {
  /**
   * Deterministic will deliver the message template in exactly the language and locale asked for while fallback will deliver the message template in user's device language,
   * if the settings can't be found on users device the fallback language is used.
   */
  policy: 'fallback' | 'deterministic';
  /** The code of the language or locale to use, accepts both language and language_locale formats (e.g., en or en_US). */
  code: languages;
}

export type HSMLocalizableParameters =
  | HSMLocalizableParametersCurrency
  | HSMLocalizableParametersDateTime;

export interface HSMLocalizableParametersCurrency {
  /**
   * Default value of the parameter, it is used when localization fails. The only field needed when specifying parameter value that doesn't require localization.
   */
  default: string;
  currency?: {
    /** string of ISO 4217 currency code */
    currencyCode: string;
    /** integer of total amount together with cents as a float, multipled by 1000 */
    amount: number;
  };
}

export interface HSMLocalizableParametersDateTime {
  /**
   * Default value of the parameter, it is used when localization fails. The only field needed when specifying parameter value that doesn't require localization.
   */
  default: string;
  /**
   * RFC3339 representation of the date and time.
   */
  dateTime?: datetime;
}

export interface SendResponse {
  message: Message;
}

export interface Message {
  /** A unique ID generated by the MessageBird platform that identifies this message. */
  id: string;
  /** The status of the message. It will be initially set to accepted. */
  status: string | 'accepted';
}

export interface UpdateConversationParameters {
  /** The new status of the conversation */
  status: 'active' | 'archived';
}

export interface ReplyConversationParameters {
  /** The unique ID that identifies the conversation */
  id: string;
}

export namespace Webhooks {
  interface CreateParameters {
    /** A list of event name strings from the list of available events that should trigger this webhook. */
    events: string[];
    /** The unique identifier for a MessageBird channel that this webhook will subcribe to events for. */
    channelId: string;
    /** The endpoint URL that requests should be sent to. */
    url: string;
  }
  interface UpdateParameters {
    /** A list of event name strings from the list of available events that should trigger this webhook. */
    events: string[];
    /** The endpoint URL that requests should be sent to. */
    url: string;
    /** Status of the webhook */
    status: 'enabled' | 'disabled';
  }
}
