name: test
on:
  pull_request:
  push:
    branches: [master, main]
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: NodeJS ${{ matrix.node }} lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run dtslint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '17', '18']
    name: NodeJS ${{ matrix.node }} test
    env:
      MB_ACCESSKEY: test_iQpAp0KCs5GCsMpDhIx2leuNB
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test
